import type { EventItem } from "@/types/event";
import { SOURCES } from "@/lib/sources";

export const FALLBACK_EVENTS: EventItem[] = [
  {
    id: "motogp-jerez-2026",
    title: "Gran Premio de España de MotoGP",
    championship: "MotoGP World Championship",
    discipline: "MotoGP",
    start: "2026-04-24",
    end: "2026-04-26",
    venue: "Circuito de Jerez - Ángel Nieto",
    city: "Jerez de la Frontera",
    province: "Cádiz",
    region: "Andalucía",
    level: "Mundial",
    source: "MotoGP",
    sourceUrl: SOURCES.MotoGP,
    ticketUrl: "https://www.circuitodejerez.com/",
    tags: ["MotoGP", "velocidad"],
    featured: true,
  },
  {
    id: "motogp-catalunya-2026",
    title: "Gran Premi de Catalunya de MotoGP",
    championship: "MotoGP World Championship",
    discipline: "MotoGP",
    start: "2026-05-15",
    end: "2026-05-17",
    venue: "Circuit de Barcelona-Catalunya",
    city: "Montmeló",
    province: "Barcelona",
    region: "Catalunya",
    level: "Mundial",
    source: "Circuit de Barcelona-Catalunya",
    sourceUrl: SOURCES.CircuitCat,
    ticketUrl: SOURCES.CircuitCat,
    tags: ["MotoGP", "velocidad"],
    featured: true,
  },
  {
    id: "motogp-aragon-2026",
    title: "Gran Premio de Aragón de MotoGP",
    championship: "MotoGP World Championship",
    discipline: "MotoGP",
    start: "2026-08-28",
    end: "2026-08-30",
    venue: "MotorLand Aragón",
    city: "Alcañiz",
    province: "Teruel",
    region: "Aragón",
    level: "Mundial",
    source: "MotorLand Aragón",
    sourceUrl: SOURCES.MotorLand,
    ticketUrl: SOURCES.MotorLand,
    tags: ["MotoGP", "velocidad"],
    featured: true,
  },
  {
    id: "motogp-valencia-2026",
    title: "Gran Premio Motul de la Comunitat Valenciana",
    championship: "MotoGP World Championship",
    discipline: "MotoGP",
    start: "2026-11-27",
    end: "2026-11-29",
    venue: "Circuit Ricardo Tormo",
    city: "Cheste",
    province: "Valencia",
    region: "Comunitat Valenciana",
    level: "Mundial",
    source: "Circuit Ricardo Tormo",
    sourceUrl: SOURCES.RicardoTormo,
    ticketUrl: SOURCES.RicardoTormo,
    tags: ["MotoGP", "final"],
    featured: true,
  },
  {
    id: "esbk-navarra-2026",
    title: "ESBK Navarra",
    championship: "Campeonato de España de Superbike",
    discipline: "Superbike",
    start: "2026-05-07",
    end: "2026-05-10",
    venue: "Circuito de Navarra",
    city: "Los Arcos",
    province: "Navarra",
    region: "Navarra",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-superbike/",
    ticketUrl: "https://www.circuitodenavarra.com/",
    tags: ["ESBK", "superbike"],
    featured: true,
  },
  {
    id: "esbk-motorland-2026",
    title: "ESBK MotorLand Aragón",
    championship: "Campeonato de España de Superbike",
    discipline: "Superbike",
    start: "2026-07-16",
    end: "2026-07-19",
    venue: "MotorLand Aragón",
    city: "Alcañiz",
    province: "Teruel",
    region: "Aragón",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-superbike/",
    ticketUrl: SOURCES.MotorLand,
    tags: ["ESBK", "superbike"],
    featured: false,
  },
  {
    id: "copa-velocidad-jerez-2026",
    title: "Copa de España de Velocidad - Jerez",
    championship: "Copa de España de Velocidad",
    discipline: "Velocidad",
    start: "2026-05-29",
    end: "2026-05-31",
    venue: "Circuito de Jerez - Ángel Nieto",
    city: "Jerez de la Frontera",
    province: "Cádiz",
    region: "Andalucía",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/copa-de-espana-de-velocidad/",
    ticketUrl: "",
    tags: ["velocidad"],
    featured: false,
  },
  {
    id: "mx-osuna-2026",
    title: "Campeonato de España de Motocross - Osuna",
    championship: "Campeonato de España de Motocross",
    discipline: "Motocross",
    start: "2026-05-02",
    end: "2026-05-03",
    venue: "Circuito de Osuna",
    city: "Osuna",
    province: "Sevilla",
    region: "Andalucía",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-motocross/",
    ticketUrl: "",
    tags: ["MX", "offroad"],
    featured: true,
  },
  {
    id: "mx-motorland-2026",
    title: "Campeonato de España de Motocross - MotorLand",
    championship: "Campeonato de España de Motocross",
    discipline: "Motocross",
    start: "2026-09-19",
    end: "2026-09-20",
    venue: "MotorLand Aragón",
    city: "Alcañiz",
    province: "Teruel",
    region: "Aragón",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-motocross/",
    ticketUrl: SOURCES.MotorLand,
    tags: ["MX", "offroad"],
    featured: false,
  },
  {
    id: "trial-gironella-2026",
    title: "Campeonato de España de Trial - Gironella",
    championship: "Campeonato de España de Trial",
    discipline: "Trial",
    start: "2026-05-30",
    end: "2026-05-31",
    venue: "Gironella",
    city: "Gironella",
    province: "Barcelona",
    region: "Catalunya",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-trial/",
    ticketUrl: "",
    tags: ["trial"],
    featured: false,
  },
  {
    id: "enduro-orista-2026",
    title: "Campeonato de España de Enduro - Oristà",
    championship: "Campeonato de España de Enduro",
    discipline: "Enduro",
    start: "2026-09-19",
    end: "2026-09-20",
    venue: "Torre d'Oristà",
    city: "Oristà",
    province: "Barcelona",
    region: "Catalunya",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/campeonato-de-espana-de-enduro/",
    ticketUrl: "",
    tags: ["enduro"],
    featured: false,
  },
  {
    id: "mini-cartagena-2026",
    title: "Copa de España de MiniVelocidad - Cartagena",
    championship: "Copa de España de MiniVelocidad",
    discipline: "MiniVelocidad",
    start: "2026-05-01",
    end: "2026-05-03",
    venue: "Circuito de Cartagena",
    city: "Cartagena",
    province: "Murcia",
    region: "Región de Murcia",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/copa-de-espana-de-minivelocidad/",
    ticketUrl: "https://www.circuitocartagena.com/",
    tags: ["minivelocidad"],
    featured: false,
  },
  {
    id: "tour-penitentes-2026",
    title: "RFME Mototurismo Touring - Penitentes",
    championship: "RFME Mototurismo Touring Challenge",
    discipline: "Mototurismo",
    start: "2026-05-01",
    end: "2026-05-01",
    venue: "Penitentes",
    city: "Pirineo aragonés",
    province: "Huesca",
    region: "Aragón",
    level: "Nacional",
    source: "RFME",
    sourceUrl: "https://rfme.com/campeonatos/copa-de-espana-de-mototurismo/",
    ticketUrl: "",
    tags: ["mototurismo"],
    featured: false,
  },
];
